var TYPES = require('tedious').TYPES;
exports = module.exports = {
  port: 3000,
  failureRetryRate: 5 * 60 * 1000, // 5 mins
  logDirectory: '/a3-qr/logs/',
  database: {
    protocol: 'postgres',
    host: 'db',
    port: 5432,
    database: 'a3qr',
    user: 'webadmin',
    password: 'a3qr',
  },
  queue: {
    type: 'sns',
    protocol: 'https',
    region: 'us-west-2',
    arn: 'arn:aws:sns:us-west-2:949953444104:a3-stg',
    endpoint: 'https://sns.us-west-2.amazonaws.com',
    messageEndpoint: 'https://a3-queue-stg.my-a3.com/message',
  },
  recipient: [
    {
      type: 'sage',
      host: 'localhost',
      port: 1433,
      database: 'a3qr',
      username: 'sa',
      password: 'A3qrpass',
      validTenants: ['sgm', 'sgmtest', 'wallem'],
      validEntities: ['company', 'emailAddress', 'port', 'nomination', 'appointment', 'event', 'eventType', 'fund', 'vessel', 'da', 'daService', 'daRevision', 'daEstimate', 'daInvoiceService', 'daInvoice'],
      entityToTable: {
        company: {
          table: 'a3_table_company',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            name: { type: TYPES.NVarChar, columnName: 'name' },
            isAgency: { type: TYPES.Bit, columnName: 'is_agency' },
            isVc: { type: TYPES.Bit, columnName: 'is_vc' },
            isCc: { type: TYPES.Bit, columnName: 'is_cc' },
            isWorkPartner: { type: TYPES.Bit, columnName: 'is_work_partner' },
            isVrsProvider: { type: TYPES.Bit, columnName: 'is_vrs_provider' },
            numVslOperated: { type: TYPES.SmallInt, columnName: 'num_vsl_operated' },
            mailToHeader: { type: TYPES.Text, columnName: 'mail_to_header' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
            doNotDelete: { type: TYPES.Bit, columnName: 'do_not_delete' },
            isSubagency: { type: TYPES.Bit, columnName: 'is_subagency' },
            hasExternalEventTypes: { type: TYPES.Bit, columnName: 'has_external_event_types' },
            companyCode: { type: TYPES.NVarChar, columnName: 'company_code' },
            customerStatus: { type: TYPES.Text, columnName: 'customer_status' },
            prefundingType: { type: TYPES.NVarChar, columnName: 'prefunding_type' },
            prefundingPercent: { type: TYPES.Int, columnName: 'prefunding_percent' },
            fileNumberSeq: { type: TYPES.Int, columnName: 'file_number_seq' },
            isActive: { type: TYPES.Bit, columnName: 'is_active' },
            isCustomer: { type: TYPES.Bit, columnName: 'is_customer' },
            isSupplier: { type: TYPES.Bit, columnName: 'is_supplier' },
            vatNumber: { type: TYPES.Text, columnName: 'vat_number' },
          },
        },
        emailAddress: {
          table: 'a3_table_email_address',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            companyId: { type: TYPES.Int, columnName: 'company_id' },
            officeId: { type: TYPES.Int, columnName: 'office_id' },
            personId: { type: TYPES.Int, columnName: 'person_id' },
            prime: { type: TYPES.Bit, columnName: 'prime' },
            description: { type: TYPES.NVarChar, columnName: 'description' },
            address: { type: TYPES.NVarChar, columnName: 'address' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
          },
        },
        office: {
          table: 'a3_table_office',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            name: { type: TYPES.NVarChar, columnName: 'name' },
            companyId: { type: TYPES.Int, columnName: 'company_id' },
            fileNumberSeq: { type: TYPES.Int, columnName: 'file_number_seq' },
            billingCodeYear: { type: TYPES.Int, columnName: 'billing_code_year' },
            address: { type: TYPES.NVarChar, columnName: 'address' },
            bankingDetails: { type: TYPES.NVarChar, columnName: 'banking_details' },
            officeBillingCode: { type: TYPES.NVarChar, columnName: 'office_billing_code' },
            prime: { type: TYPES.Bit, columnName: 'prime' },
            mailToHeader: { type: TYPES.Text, columnName: 'mail_to_header' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
          },
        },
        port: {
          table: 'a3_table_port',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            name: { type: TYPES.NVarChar, columnName: 'name' },
            countryId: { type: TYPES.Int, columnName: 'country_id' },
            longitude: { type: TYPES.NVarChar, columnName: 'longitude' },
            latitude: { type: TYPES.NVarChar, columnName: 'latitude' },
            restrictions: { type: TYPES.Text, columnName: 'restrictions' },
            notes: { type: TYPES.Text, columnName: 'notes' },
            url: { type: TYPES.Text, columnName: 'url' },
            gifFilename: { type: TYPES.NVarChar, columnName: 'gif_filename' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
          },
        },
        nomination: {
          table: 'a3_table_nomination',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            appointmentId: { type: TYPES.Int, columnName: 'appointment_id' },
            vesselId: { type: TYPES.Int, columnName: 'vessel_id' },
            nominatingPartyId: { type: TYPES.Int, columnName: 'nominating_party_id' },
            portId: { type: TYPES.Int, columnName: 'port_id' },
            voyageNumber: { type: TYPES.NVarChar, columnName: 'voyage_number' },
            tenArrivalDate: { type: TYPES.Date, columnName: 'ten_arrival_date' },
            purpose: { type: TYPES.Text, columnName: 'purpose' },
            dateReceived: { type: TYPES.Date, columnName: 'date_received' },
            transportSpecialist: { type: TYPES.NVarChar, columnName: 'transport_specialist' },
            charterPartyDate: { type: TYPES.Date, columnName: 'charter_party_date' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
            terminalId: { type: TYPES.Int, columnName: 'terminal_id' },
            hubReference: { type: TYPES.NVarChar, columnName: 'hub_reference' },
            nominationNumber: { type: TYPES.NVarChar, columnName: 'nomination_number' },
            isVesselTbn: { type: TYPES.Bit, columnName: 'is_vessel_tbn' },
            leadAgentId: { type: TYPES.Int, columnName: 'lead_agent_id' },
            typeId: { type: TYPES.Int, columnName: 'type_id' },
            status: { type: TYPES.NVarChar, columnName: 'status' },
            principalId: { type: TYPES.Int, columnName: 'principal_id' },
            pdaFunded: { type: TYPES.Bit, columnName: 'pda_funded' },
            daCompleted: { type: TYPES.Bit, columnName: 'da_completed' },
            nominatingThirdPartyId: { type: TYPES.Int, columnName: 'nominating_third_party_id' },
            subagencyId: { type: TYPES.Int, columnName: 'subagency_id' },
            subagencyOfficeId: { type: TYPES.Int, columnName: 'subagency_office_id' },
            approvedDate: { type: TYPES.DateTimeOffset, columnName: 'approved_date' },
            isApproved: { type: TYPES.Bit, columnName: 'is_approved' },
          },
        },
        appointment: {
          table: 'a3_table_appointment',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            agencyOfficeId: { type: TYPES.Int, columnName: 'agency_office_id' },
            businessTypeId: { type: TYPES.Int, columnName: 'business_type_id' },
            fromPortId: { type: TYPES.Int, columnName: 'from_port_id' },
            toPortId: { type: TYPES.Int, columnName: 'to_port_id' },
            nextPortId: { type: TYPES.Int, columnName: 'next_port_id' },
            destPortId: { type: TYPES.Int, columnName: 'dest_port_id' },
            appType: { type: TYPES.Int, columnName: 'app_type' },
            appStatus: { type: TYPES.NVarChar, columnName: 'app_status' },
            vesselCurrentStatus: { type: TYPES.NVarChar, columnName: 'vessel_current_status' },
            vesselCtrlrId: { type: TYPES.Int, columnName: 'vessel_ctrlr_id' },
            leadAgent: { type: TYPES.Int, columnName: 'lead_agent' },
            fileNumber: { type: TYPES.NVarChar, columnName: 'file_number' },
            appointmentDate: { type: TYPES.Date, columnName: 'appointment_date' },
            terminals: { type: TYPES.Text, columnName: 'terminals' },
            berths: { type: TYPES.Text, columnName: 'berths' },
            tugCompanyId: { type: TYPES.Int, columnName: 'tug_company_id' },
            launchCompanyId: { type: TYPES.Int, columnName: 'launch_company_id' },
            transportCompanyId: { type: TYPES.Int, columnName: 'transport_company_id' },
            linehandlineCompanyId: { type: TYPES.Int, columnName: 'linehandline_company_id' },
            medicalCompanyId: { type: TYPES.Int, columnName: 'medical_company_id' },
            summaryNote: { type: TYPES.Text, columnName: 'summary_note' },
            advanceRequestedWhen: { type: TYPES.Date, columnName: 'advance_requested_when' },
            advanceRequestedAmount: { type: TYPES.Numeric, columnName: 'advance_requested_amount' },
            dateFirstAdvancedReceived: { type: TYPES.Date, columnName: 'date_first_advanced_received' },
            amountReceived: { type: TYPES.Numeric, columnName: 'amount_received' },
            calculatedTimeInPort: { type: TYPES.NVarChar, columnName: 'calculated_time_in_port' },
            dateCompleted: { type: TYPES.DateTimeOffset, columnName: 'date_completed' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
            lastPortId1: { type: TYPES.Int, columnName: 'last_port_id1' },
            lastPortId2: { type: TYPES.Int, columnName: 'last_port_id2' },
            lastPortId3: { type: TYPES.Int, columnName: 'last_port_id3' },
            lastPortId4: { type: TYPES.Int, columnName: 'last_port_id4' },
            lastPortId5: { type: TYPES.Int, columnName: 'last_port_id5' },
            subagencyOfficeId: { type: TYPES.Int, columnName: 'subagency_office_id' },
            subagencyId: { type: TYPES.Int, columnName: 'subagency_id' },
            minEventId: { type: TYPES.Int, columnName: 'min_event_id' },
            minEventName: { type: TYPES.NVarChar, columnName: 'min_event_name' },
            minEventDate: { type: TYPES.DateTimeOffset, columnName: 'min_event_date' },
            maxEventId: { type: TYPES.Int, columnName: 'max_event_id' },
            maxEventName: { type: TYPES.NVarChar, columnName: 'max_event_name' },
            maxEventDate: { type: TYPES.DateTimeOffset, columnName: 'max_event_date' },
            minNnEventId: { type: TYPES.Int, columnName: 'min_nn_event_id' },
            minNnEventName: { type: TYPES.NVarChar, columnName: 'min_nn_event_name' },
            minNnEventDate: { type: TYPES.DateTimeOffset, columnName: 'min_nn_event_date' },
            maxNnEventId: { type: TYPES.Int, columnName: 'max_nn_event_id' },
            maxNnEventName: { type: TYPES.NVarChar, columnName: 'max_nn_event_name' },
            maxNnEventDate: { type: TYPES.DateTimeOffset, columnName: 'max_nn_event_date' },
            totalDaActualCost: { type: TYPES.Numeric, columnName: 'total_da_actual_cost' },
            isDaFunded: { type: TYPES.Bit, columnName: 'is_da_funded' },
            daFundedModifiedBy: { type: TYPES.Int, columnName: 'da_funded_modified_by' },
            daFundedLastModified: { type: TYPES.DateTimeOffset, columnName: 'da_funded_last_modified' },
            vesselControllerPersonId: { type: TYPES.Int, columnName: 'vessel_controller_person_id' },
            customsBrokerCompanyId: { type: TYPES.Int, columnName: 'customs_broker_company_id' },
            oilSpillResponseCompanyId: { type: TYPES.Int, columnName: 'oil_spill_response_company_id' },
            bunkerSupplierCompanyId: { type: TYPES.Int, columnName: 'bunker_supplier_company_id' },
            bunkerBrokerCompanyId: { type: TYPES.Int, columnName: 'bunker_broker_company_id' },
            defaultMessageSubject: { type: TYPES.NVarChar, columnName: 'default_message_subject' },
            dateCreated: { type: TYPES.DateTime, columnName: 'date_created' },
            fileNumberType: { type: TYPES.NVarChar, columnName: 'file_number_type' },
            vesselNameForDocuments: { type: TYPES.NVarChar, columnName: 'vessel_name_for_documents' },
            locale: { type: TYPES.NVarChar, columnName: 'locale' },
            pfda: { type: TYPES.Bit, columnName: 'pfda' },
            todoTotal: { type: TYPES.Int, columnName: 'todo_total' },
            todoUpcoming: { type: TYPES.Int, columnName: 'todo_upcoming' },
            todoUrgent: { type: TYPES.Int, columnName: 'todo_urgent' },
            isDaCompleted: { type: TYPES.Bit, columnName: 'is_da_completed' },
            isApproved: { type: TYPES.Bit, columnName: 'is_approved' },
            approvedDate: { type: TYPES.DateTimeOffset, columnName: 'approved_date' },
          },
        },
        event: {
          table: 'a3_table_event',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            typeId: { type: TYPES.Int, columnName: 'type_id' },
            appointmentId: { type: TYPES.Int, columnName: 'appointment_id' },
            startDate: { type: TYPES.Date, columnName: 'start_date' },
            startTime: { type: TYPES.Time, columnName: 'start_time' },
            stopDate: { type: TYPES.Date, columnName: 'stop_date' },
            stopTime: { type: TYPES.Time, columnName: 'stop_time' },
            notation: { type: TYPES.Text, columnName: 'notation' },
            includeOnLog: { type: TYPES.Bit, columnName: 'include_on_log' },
            sendInNextMsg: { type: TYPES.Bit, columnName: 'send_in_next_msg' },
            created: { type: TYPES.DateTimeOffset, columnName: 'created' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
            cargoId: { type: TYPES.Int, columnName: 'cargo_id' },
            terminalId: { type: TYPES.Int, columnName: 'terminal_id' },
            startTimezone: { type: TYPES.NVarChar, columnName: 'start_timezone' },
            stopTimezone: { type: TYPES.NVarChar, columnName: 'stop_timezone' },
            portId: { type: TYPES.Int, columnName: 'port_id' },
            nominationId: { type: TYPES.Int, columnName: 'nomination_id' },
            sortOrder: { type: TYPES.Int, columnName: 'sort_order' },
            docId: { type: TYPES.Int, columnName: 'doc_id' },
            originalEventId: { type: TYPES.Int, columnName: 'original_event_id' },
          },
        },
        eventType: {
          table: 'a3_table_event_type',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            type: { type: TYPES.NVarChar, columnName: 'type' },
            tableName: { type: TYPES.NVarChar, columnName: 'table_name' },
            templateName: { type: TYPES.NVarChar, columnName: 'template_name' },
            hasStop: { type: TYPES.Bit, columnName: 'has_stop' },
            showNotation: { type: TYPES.Bit, columnName: 'show_notation' },
            enabled: { type: TYPES.Bit, columnName: 'enabled' },
            isWorkStoppage: { type: TYPES.Bit, columnName: 'is_work_stoppage' },
            includeOnSofDefault: { type: TYPES.Bit, columnName: 'include_on_sof_default' },
            performancingTypeId: { type: TYPES.Int, columnName: 'performancing_type_id' },
            performancingSortOrder: { type: TYPES.Int, columnName: 'performancing_sort_order' },
            isRequired: { type: TYPES.Bit, columnName: 'is_required' },
          },
        },
        fund: {
          table: 'a3_table_fund',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            dateReceived: { type: TYPES.DateTime, columnName: 'date_received' },
            payeeCompanyId: { type: TYPES.Int, columnName: 'payee_company_id' },
            category: { type: TYPES.NVarChar, columnName: 'category' },
            comment: { type: TYPES.Text, columnName: 'comment' },
            amount: { type: TYPES.Numeric, columnName: 'amount' },
            appointmentId: { type: TYPES.Int, columnName: 'appointment_id' },
            portId: { type: TYPES.Int, columnName: 'port_id' },
            nominationId: { type: TYPES.Int, columnName: 'nomination_id' },
            externalSource: { type: TYPES.NVarChar, columnName: 'external_source' },
            externalId: { type: TYPES.Int, columnName: 'external_id' },
          },
        },
        vessel: {
          table: 'a3_table_vessel',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            vesselTypeId: { type: TYPES.Int, columnName: 'vessel_type_id' },
            disponentOwnerCompanyId: { type: TYPES.Int, columnName: 'disponent_owner_company_id' },
            name: { type: TYPES.NVarChar, columnName: 'name' },
            isProblemVessel: { type: TYPES.Bit, columnName: 'is_problem_vessel' },
            generalDetails: { type: TYPES.Text, columnName: 'general_details' },
            lastPreviousName: { type: TYPES.NVarChar, columnName: 'last_previous_name' },
            callSign: { type: TYPES.NVarChar, columnName: 'call_sign' },
            flag: { type: TYPES.NVarChar, columnName: 'flag' },
            previousFlag: { type: TYPES.NVarChar, columnName: 'previous_flag' },
            class: { type: TYPES.NVarChar, columnName: 'class' },
            registry: { type: TYPES.NVarChar, columnName: 'registry' },
            loa: { type: TYPES.NVarChar, columnName: 'loa' },
            beam: { type: TYPES.NVarChar, columnName: 'beam' },
            mastersName: { type: TYPES.NVarChar, columnName: 'masters_name' },
            yearBuilt: { type: TYPES.SmallInt, columnName: 'year_built' },
            builder: { type: TYPES.NVarChar, columnName: 'builder' },
            lastThreeCargoes: { type: TYPES.Text, columnName: 'last_three_cargoes' },
            fullSummerDeadweight: { type: TYPES.NVarChar, columnName: 'full_summer_deadweight' },
            fullSummerDraft: { type: TYPES.NVarChar, columnName: 'full_summer_draft' },
            freeboardInSbtCondition: { type: TYPES.NVarChar, columnName: 'freeboard_in_sbt_condition' },
            freeboardInLightCondition: { type: TYPES.NVarChar, columnName: 'freeboard_in_light_condition' },
            freeboardOnFullSummerDraft: { type: TYPES.NVarChar, columnName: 'freeboard_on_full_summer_draft' },
            intlNetRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'intl_net_registered_tonnage' },
            intlGrossRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'intl_gross_registered_tonnage' },
            suezNetRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'suez_net_registered_tonnage' },
            suezGrossRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'suez_gross_registered_tonnage' },
            panamaNetRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'panama_net_registered_tonnage' },
            panamaGrossRegisteredTonnage: { type: TYPES.NVarChar, columnName: 'panama_gross_registered_tonnage' },
            tpcImmersionAtSummerDraft: { type: TYPES.NVarChar, columnName: 'tpc_immersion_at_summer_draft' },
            draftNormBallastConds: { type: TYPES.NVarChar, columnName: 'draft_norm_ballast_conds' },
            parallelBodyLenLightCond: { type: TYPES.NVarChar, columnName: 'parallel_body_len_light_cond' },
            parallelBodyLenBallastCond: { type: TYPES.NVarChar, columnName: 'parallel_body_len_ballast_cond' },
            parallelBodyLenLadenCond: { type: TYPES.NVarChar, columnName: 'parallel_body_len_laden_cond' },
            ktm: { type: TYPES.NVarChar, columnName: 'ktm' },
            pAndIClubName: { type: TYPES.NVarChar, columnName: 'p_and_i_club_name' },
            pollutionIncidents: { type: TYPES.Text, columnName: 'pollution_incidents' },
            groundingCollisionIncidents: { type: TYPES.Text, columnName: 'grounding_collision_incidents' },
            pscOutstandingDeficiencies: { type: TYPES.Bit, columnName: 'psc_outstanding_deficiencies' },
            pscDeficienciesDetails: { type: TYPES.Text, columnName: 'psc_deficiencies_details' },
            subjectToConditionsOfClass: { type: TYPES.Bit, columnName: 'subject_to_conditions_of_class' },
            detailsOfConditions: { type: TYPES.Text, columnName: 'details_of_conditions' },
            classificationSociety: { type: TYPES.NVarChar, columnName: 'classification_society' },
            classNotation: { type: TYPES.NVarChar, columnName: 'class_notation' },
            previousClassificationSociety: { type: TYPES.NVarChar, columnName: 'previous_classification_society' },
            previousClassNotation: { type: TYPES.NVarChar, columnName: 'previous_class_notation' },
            hasBulousBow: { type: TYPES.Bit, columnName: 'has_bulous_bow' },
            numYearsOperatedByVc: { type: TYPES.SmallInt, columnName: 'num_years_operated_by_vc' },
            officerNationality: { type: TYPES.NVarChar, columnName: 'officer_nationality' },
            crewNationality: { type: TYPES.NVarChar, columnName: 'crew_nationality' },
            helicopterAreaType: { type: TYPES.NVarChar, columnName: 'helicopter_area_type' },
            helicopterCircleDiameter: { type: TYPES.NVarChar, columnName: 'helicopter_circle_diameter' },
            ballastTanksCoatedType: { type: TYPES.NVarChar, columnName: 'ballast_tanks_coated_type' },
            ballastTankCoatingCondition: { type: TYPES.NVarChar, columnName: 'ballast_tank_coating_condition' },
            typeOfBallast: { type: TYPES.NVarChar, columnName: 'type_of_ballast' },
            safeWorkingLoadOfDerrick: { type: TYPES.NVarChar, columnName: 'safe_working_load_of_derrick' },
            hullType: { type: TYPES.NVarChar, columnName: 'hull_type' },
            itfCertification: { type: TYPES.NVarChar, columnName: 'itf_certification' },
            hadPollutionIncidentIn12Mo: { type: TYPES.Bit, columnName: 'had_pollution_incident_in_12_mo' },
            hadGroundingInLast12Mo: { type: TYPES.Bit, columnName: 'had_grounding_in_last_12_mo' },
            hadCollisionInLast12Mo: { type: TYPES.Bit, columnName: 'had_collision_in_last_12_mo' },
            radarsGyroStabilized: { type: TYPES.Bit, columnName: 'radars_gyro_stabilized' },
            vesselCarriesSextants: { type: TYPES.Bit, columnName: 'vessel_carries_sextants' },
            vesselCarriesSignalLamps: { type: TYPES.Bit, columnName: 'vessel_carries_signal_lamps' },
            bridgeFittedWRudderAnglInd: { type: TYPES.Bit, columnName: 'bridge_fitted_w_rudder_angl_ind' },
            bridgeFittedWRpmIndicator: { type: TYPES.Bit, columnName: 'bridge_fitted_w_rpm_indicator' },
            bridgeFittedWGyroRepeater: { type: TYPES.Bit, columnName: 'bridge_fitted_w_gyro_repeater' },
            bridgeEquipWDeadManAlarm: { type: TYPES.Bit, columnName: 'bridge_equip_w_dead_man_alarm' },
            bridgeFittedWMotEngCtrls: { type: TYPES.Bit, columnName: 'bridge_fitted_w_mot_eng_ctrls' },
            hasOperatedQmOrSafetySys: { type: TYPES.Bit, columnName: 'has_operated_qm_or_safety_sys' },
            operatedQmOrSafetySys: { type: TYPES.Text, columnName: 'operated_qm_or_safety_sys' },
            qmSafetySysCertificBody: { type: TYPES.NVarChar, columnName: 'qm_safety_sys_certific_body' },
            dateOfVesselCertification: { type: TYPES.Date, columnName: 'date_of_vessel_certification' },
            opa90HasSubmittedSpillPlan: { type: TYPES.Bit, columnName: 'opa90_has_submitted_spill_plan' },
            opa90HasFiledAppndxWports: { type: TYPES.Bit, columnName: 'opa90_has_filed_appndx_wports' },
            opa90HasSigndServiceContrcs: { type: TYPES.Bit, columnName: 'opa90_has_signd_service_contrcs' },
            created: { type: TYPES.DateTimeOffset, columnName: 'created' },
            lastModified: { type: TYPES.DateTimeOffset, columnName: 'last_modified' },
            modPersonId: { type: TYPES.Int, columnName: 'mod_person_id' },
            imoCode: { type: TYPES.NVarChar, columnName: 'imo_code' },
            isHidden: { type: TYPES.Bit, columnName: 'is_hidden' },
            fullWinterDraft: { type: TYPES.NVarChar, columnName: 'full_winter_draft' },
            gearInformation: { type: TYPES.Text, columnName: 'gear_information' },
            numberOfCrew: { type: TYPES.SmallInt, columnName: 'number_of_crew' },
            registrationCertificateNumber: { type: TYPES.NVarChar, columnName: 'registration_certificate_number' },
            registrationCertificateExpiry: {
              type: TYPES.DateTimeOffset,
              columnName: 'registration_certificate_expiry'
            },
            fullTimberDraft: { type: TYPES.NVarChar, columnName: 'full_timber_draft' },
            fullWinterDeadweight: { type: TYPES.NVarChar, columnName: 'full_winter_deadweight' },
            fullTimberDeadweight: { type: TYPES.NVarChar, columnName: 'full_timber_deadweight' },
            shipdbImportDate: { type: TYPES.DateTime, columnName: 'shipdb_import_date' },
          },
        },
        da: {
          table: 'a3_table_da',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            appointmentId: { type: TYPES.Int, columnName: 'appointment_id' },
            publicationId: { type: TYPES.NVarChar, columnName: 'publication_id' },
            nominationId: { type: TYPES.Int, columnName: 'nomination_id' },
            vesselId: { type: TYPES.Int, columnName: 'vessel_id' },
            principalId: { type: TYPES.Int, columnName: 'principal_id' },
            portId: { type: TYPES.Int, columnName: 'port_id' },
            currentRevisionId: { type: TYPES.Int, columnName: 'current_revision_id' },
            currency: { type: TYPES.NVarChar, columnName: 'currency' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
            fundedAt: { type: TYPES.DateTime, columnName: 'funded_at' },
            completedAt: { type: TYPES.DateTime, columnName: 'completed_at' },
            externalReference: { type: TYPES.NVarchar, columnName: 'external_reference' },
          },
        },
        daService: {
          table: 'a3_table_da_service',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            daId: { type: TYPES.Int, columnName: 'da_id' },
            code: { type: TYPES.NVarChar, columnName: 'code' },
            description: { type: TYPES.Text, columnName: 'description' },
            category: { type: TYPES.NVarChar, columnName: 'category' },
            supplierId: { type: TYPES.Int, columnName: 'supplier_id' },
            requesterId: { type: TYPES.Int, columnName: 'requester_id' },
            invoiceId: { type: TYPES.Int, columnName: 'invoice_id' },
            supplierInvoiceId: { type: TYPES.Int, columnName: 'supplier_invoice_id' },
            cost: { type: TYPES.Numeric, columnName: 'cost' },
            costWithTax: { type: TYPES.Numeric, columnName: 'cost_with_tax' },
            costCurrency: { type: TYPES.NVarChar, columnName: 'cost_currency' },
            activityCode: { type: TYPES.NVarChar, columnName: 'activity_code' },
            suppliedAt: { type: TYPES.DateTime, columnName: 'supplied_at' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
            externalReference: { type: TYPES.NVarchar, columnName: 'external_reference' },
          },
        },
        daRevision: {
          table: 'a3_table_da_revision',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            daId: { type: TYPES.Int, columnName: 'da_id' },
            status: { type: TYPES.NVarChar, columnName: 'status' },
            revisionNumber: { type: TYPES.Int, columnName: 'revision_number' },
            reference: { type: TYPES.NVarChar, columnName: 'reference' },
            taxExempt: { type: TYPES.Bit, columnName: 'tax_exempt' },
            amount: { type: TYPES.Numeric, columnName: 'amount' },
            amountWithTax: { type: TYPES.Numeric, columnName: 'amount_with_tax' },
            data: { type: TYPES.Text, columnName: 'data' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
            modifiedBy: { type: TYPES.Int, columnName: 'modified_by' },
            createdBy: { type: TYPES.Int, columnName: 'created_by' },
          },
        },
        daEstimate: {
          table: 'a3_table_da_revision_estimate',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            daRevisionId: { type: TYPES.Int, columnName: 'da_revision_id' },
            compulsory: { type: TYPES.Bit, columnName: 'compulsory' },
            overridden: { type: TYPES.Bit, columnName: 'overridden' },
            disabled: { type: TYPES.Bit, columnName: 'disabled' },
            amount: { type: TYPES.Numeric, columnName: 'amount' },
            amountWithTax: { type: TYPES.Numeric, columnName: 'amount_with_tax' },
            sortOrder: { type: TYPES.Int, columnName: 'sort_order' },
            comment: { type: TYPES.Text, columnName: 'comment' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
            daServiceId: { type: TYPES.Int, columnName: 'da_service_id' },
          },
        },
        daInvoice: {
          table: 'a3_table_da_invoice',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            daId: { type: TYPES.Int, columnName: 'da_id' },
            companyId: { type: TYPES.Int, columnName: 'company_id' },
            reference: { type: TYPES.NVarChar, columnName: 'reference' },
            amount: { type: TYPES.Numeric, columnName: 'amount' },
            amountWithTax: { type: TYPES.Numeric, columnName: 'amount_with_tax' },
            currency: { type: TYPES.NVarChar, columnName: 'currency' },
            issuedAt: { type: TYPES.DateTime, columnName: 'issued_at' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
            fileID: { type: TYPES.Int, columnName: 'file_id' },
          },
        },
        daInvoiceService: {
          table: 'a3_table_da_invoice_service',
          fields: {
            id: { type: TYPES.Int, columnName: 'id', primaryKey: true },
            daInvoiceId: { type: TYPES.Int, columnName: 'da_invoice_id' },
            code: { type: TYPES.NVarChar, columnName: 'code' },
            description: { type: TYPES.Text, columnName: 'description' },
            amount: { type: TYPES.Numeric, columnName: 'amount' },
            amountWithTax: { type: TYPES.Numeric, columnName: 'amount_with_tax' },
            createdAt: { type: TYPES.DateTime, columnName: 'created_at' },
            updatedAt: { type: TYPES.DateTime, columnName: 'updated_at' },
          },
        },
      },
    }
  ]
};
